local function GetPhrase(text)
    return language.GetPhrase(text)
end

hook.Add("PopulateToolMenu", "TRM_weapon_base_q_menu", function()
    spawnmenu.AddToolMenuOption("TriggerMiku_Work", "TRM Gun Base", "trmbase_admin", "Admin", "", "", function(panel)
        panel:ClearControls()
        panel:CheckBox(GetPhrase("TRMBase_InfiniteAmmo"), "trmbase_infinite_ammo")
        panel:CheckBox(GetPhrase("TRMBase_AutoReload"), "trmbase_autoreload")
        panel:CheckBox(GetPhrase("TRMBase_FireInteruptReload"), "trmbase_fire_interupt_reload")
        panel:CheckBox(GetPhrase("TRMBase_SprintReload"), "trmbase_allow_sprintreload")
        panel:CheckBox(GetPhrase("TRMBase_LoadAttOnPickup"), "trmbase_load_attachment_on_pickup")
        panel:CheckBox(GetPhrase("TRMBase_Holster"), "trmbase_sv_holster_on_ladder")
        panel:CheckBox(GetPhrase("TRMBase_AllowSprint"), "trmbase_sv_sprint")
        panel:CheckBox(GetPhrase("TRMBase_ReloadSprint"), "trmbase_sv_reload_slowdown")
    end)
    spawnmenu.AddToolMenuOption("TriggerMiku_Work", "TRM Gun Base", "trmbase_admin_bullet", "Bullet", "", "",
        function(panel)
            panel:ClearControls()
            panel:CheckBox(GetPhrase("TRMBase_Physical_Bullet"), "trmbase_sv_physical_bullet")
        end)

    spawnmenu.AddToolMenuOption("TriggerMiku_Work", "TRM Gun Base", "trmbase_admin_mod", "Mod", "", "",
        function(panel)
            panel:ClearControls()
            panel:NumSlider(GetPhrase("TRMBase_Mod_Shake"), "trmbase_sv_mod_shake", 0, 10, 1)
            panel:NumSlider(GetPhrase("TRMBase_Mod_VisualRecoil"), "trmbase_sv_mod_visual_recoil", 0, 10, 1)
            panel:NumSlider(GetPhrase("TRMBase_Mod_Recoil"), "trmbase_sv_mod_recoil", 0, 10, 1)
            panel:NumSlider(GetPhrase("TRMBase_Mod_AimSpeed"), "trmbase_sv_mod_aimspeed", 0, 10, 1)
            panel:NumSlider(GetPhrase("TRMBase_Mod_Damage"), "trmbase_sv_mod_damage", 0, 10, 1)
        end)
    spawnmenu.AddToolMenuOption("TriggerMiku_Work", "TRM Gun Base", "trmbase_npc", "NPC", "", "", function(panel)
        panel:ClearControls()
        panel:CheckBox(GetPhrase("TRMBase_ReplaceWeapon"), "trmbase_replace_weapon")
    end)
    spawnmenu.AddToolMenuOption("TriggerMiku_Work", "TRM Gun Base", "trmbase_client", "Client", "", "", function(panel)
        panel:ClearControls()
        panel:KeyBinder(GetPhrase("TRMBase_MeleeKey"), "trmbase_cl_keybind_melee", GetPhrase("TRMBase_CustomizeKey"),
            "trmbase_cl_keybind_customize")
        panel:KeyBinder(GetPhrase("TRMBase_InspectKey"), "trmbase_cl_keybind_inspect",
            GetPhrase("TRMBase_UnderBarrelKey"), "trmbase_cl_keybind_ub")
        panel:CheckBox(GetPhrase("TRMBase_Crosshair"), "trmbase_crosshair_enable")
        panel:ColorPicker(GetPhrase("TRMBase_CrosshairColor"), "trmbase_crosshair_color_r",
            "trmbase_crosshair_color_g", "trmbase_crosshair_color_b", "trmbase_crosshair_alpha")
        panel:NumSlider(GetPhrase("TRMBase_CrosshairWidth"), "trmbase_crosshair_width", 1, 200, 0)
        panel:NumSlider(GetPhrase("TRMBase_CrosshairHeight"), "trmbase_crosshair_height", 1, 200, 0)
        panel:NumSlider(GetPhrase("TRMBase_CrosshairOutline"), "trmbase_crosshair_outline", 1, 10, 0)
        panel:NumSlider(GetPhrase("TRMBase_CrosshairScale"), "trmbase_crosshair_scale", 0.01, 5, 2)
        panel:CheckBox(GetPhrase("TRMBase_CrosshairDot"), "trmbase_crosshair_dot")
        panel:CheckBox(GetPhrase("TRMBase_HideHUDInspect"), "trmbase_hidehud_inspect")
        panel:CheckBox(GetPhrase("TRMBase_ToggleAim"), "trmbase_toggle_aim")
        panel:NumSlider(GetPhrase("TRMBase_MDV"), "trmbase_sight_mdv", 0, 3, 2)
        panel:CheckBox(GetPhrase("TRMBase_CheapScope"), "trmbase_cl_cheapscope")
    end)

    spawnmenu.AddToolMenuOption("TriggerMiku_Work", "TRM Gun Base", "trmbase_effect", "Effect", "", "", function(panel)
        panel:ClearControls()
        panel:CheckBox(GetPhrase("TRMBase_3D2D"), "trmbase_cl_3d2d")
        panel:CheckBox(GetPhrase("TRMBase_3D2D_Always"), "trmbase_cl_3d2d_always")
        panel:CheckBox(GetPhrase("TRMBase_Blur"), "trmbase_cl_blur")
        panel:CheckBox(GetPhrase("TRMBase_ShootingBlur"), "trmbase_cl_shootfx")
    end)
    spawnmenu.AddToolMenuOption("TriggerMiku_Work", "TRM Gun Base", "trmbase_develop", "Develop", "", "", function(panel)
        panel:ClearControls()
        panel:CheckBox("冻结 VM (Freeze VM)", "trmbase_freeze_vm")
        panel:CheckBox("Debug HUD", "trmbase_debug_hud")
        panel:CheckBox("Debug Reload", "trmbase_debug_reload")
    end)
    spawnmenu.AddToolMenuOption("TriggerMiku_Work", "TRM Gun Base", "trmbase_viewmodel", "ViewModel", "", "",
        function(panel)
            panel:ClearControls()
            panel:NumSlider(GetPhrase("TRMBase_OffsetX"), "trmbase_vm_offsetX", -10, 10, 1)
            panel:NumSlider(GetPhrase("TRMBase_OffsetY"), "trmbase_vm_offsetY", -10, 10, 1)
            panel:NumSlider(GetPhrase("TRMBase_OffsetZ"), "trmbase_vm_offsetZ", -10, 10, 1)
            panel:NumSlider(GetPhrase("TRMBase_ViewmodelFOVAim"), "trmbase_cl_viewmodelfov_aim", 0, 3, 2)
        end)
end)

--RunConsoleCommand("spawnmenu_reload")
