
hook.Add("PopulateToolMenu","TRM_weapon_base_q_menu",function()
    spawnmenu.AddToolMenuOption("TriggerMiku_Work","WeaponBase","trmbase_admin","Admin","","",function(panel)
        panel:ClearControls()
        panel:CheckBox(language.GetPhrase("TRMBase_InfiniteAmmo"),"trmbase_infinite_ammo")
        panel:CheckBox(language.GetPhrase("TRMBase_AutoReload"),"trmbase_autoreload")
        panel:CheckBox(language.GetPhrase("TRMBase_FireInteruptReload"),"trmbase_fire_interupt_reload")
        panel:CheckBox(language.GetPhrase("TRMBase_SprintReload"),"trmbase_allow_sprintreload")
        panel:CheckBox(language.GetPhrase("TRMBase_LoadAttOnPickup"),"trmbase_load_attachment_on_pickup")
        panel:CheckBox(language.GetPhrase("TRMBase_Holster"), "trmbase_sv_holster_on_ladder")
    end)

    spawnmenu.AddToolMenuOption("TriggerMiku_Work", "WeaponBase", "trmbase_admin_bullet", "Bullet", "", "", function(panel)
        panel:ClearControls()
            panel:CheckBox(language.GetPhrase("TRMBase_Physical_Bullet"), "trmbase_sv_physical_bullet")
        end)

    spawnmenu.AddToolMenuOption("TriggerMiku_Work", "WeaponBase", "trmbase_admin_mod", "Mod", "", "",
        function(panel)
            panel:ClearControls()
            panel:NumSlider(language.GetPhrase("TRMBase_Mod_Shake"),  "trmbase_sv_mod_shake" , 0, 10 , 1         )
            panel:NumSlider(language.GetPhrase("TRMBase_Mod_VisualRecoil"), "trmbase_sv_mod_visual_recoil", 0, 10, 1)
            panel:NumSlider(language.GetPhrase("TRMBase_Mod_Recoil"), "trmbase_sv_mod_recoil", 0, 10, 1)
            panel:NumSlider(language.GetPhrase("TRMBase_Mod_AimSpeed"), "trmbase_sv_mod_aimspeed", 0, 10, 1)
            panel:NumSlider(language.GetPhrase("TRMBase_Mod_Damage"), "trmbase_sv_mod_damage", 0, 10, 1)
        end)
    spawnmenu.AddToolMenuOption("TriggerMiku_Work", "WeaponBase", "trmbase_npc", "NPC", "", "", function(panel)
        panel:ClearControls()
        panel:CheckBox(language.GetPhrase("TRMBase_ReplaceNPC"),"trmbase_replace_npc")
        panel:CheckBox(language.GetPhrase("TRMBase_ReplaceWeapon"),"trmbase_replace_weapon")
        panel:NumSlider(language.GetPhrase("TRMBase_ReplaceChance"),"trmbase_replace_chance",0,100,0)
        panel:CheckBox(language.GetPhrase("TRMBase_RandomAttach"),"trmbase_random_attachments")
    end)
    spawnmenu.AddToolMenuOption("TriggerMiku_Work","WeaponBase","trmbase_client","Client","","",function(panel)
        panel:ClearControls()
        panel:CheckBox("TRM Tactical HUD", "trmbase_hud_enable")
        panel:CheckBox("Hide default HL2 HUD", "trmbase_hud_hide_default")
        panel:NumSlider("TRM HUD Scale", "trmbase_hud_scale", 0.75, 1.35, 2)
        panel:KeyBinder(language.GetPhrase("TRMBase_MeleeKey"),"trmbase_cl_keybind_melee")
        panel:KeyBinder(language.GetPhrase("TRMBase_InspectKey"),"trmbase_cl_keybind_inspect")
        panel:KeyBinder(language.GetPhrase("TRMBase_CustomizeKey"),"trmbase_cl_keybind_customize")
        panel:KeyBinder(language.GetPhrase("TRMBase_UnderBarrelKey"), "trmbase_cl_keybind_ub")
        panel:CheckBox(language.GetPhrase("TRMBase_Crosshair"), "trmbase_crosshair_enable")
        panel:ColorPicker(language.GetPhrase("TRMBase_CrosshairColor"), "trmbase_crosshair_color_r",
            "trmbase_crosshair_color_g", "trmbase_crosshair_color_b", "trmbase_crosshair_alpha")
        panel:NumSlider(language.GetPhrase("TRMBase_CrosshairStyle"), "trmbase_crosshair_style", 1, 3, 0)
        panel:CheckBox(language.GetPhrase("TRMBase_CrosshairDot"),"trmbase_crosshair_dot")
        panel:CheckBox(language.GetPhrase("TRMBase_HideHUDInspect"),"trmbase_hidehud_inspect")
        panel:CheckBox(language.GetPhrase("TRMBase_ToggleAim"), "trmbase_toggle_aim")
        panel:NumSlider(language.GetPhrase("TRMBase_MDV"), "trmbase_sight_mdv", 0, 3, 2)
        panel:CheckBox(language.GetPhrase("TRMBase_CheapScope"), "trmbase_cl_cheapscope")
    end)
    spawnmenu.AddToolMenuOption("TriggerMiku_Work", "WeaponBase", "trmbase_develop", "Develop", "", "", function(panel)
        panel:ClearControls()
        panel:CheckBox("冻结 VM (Freeze VM)","trmbase_freeze_vm")
        panel:CheckBox("Debug HUD", "trmbase_debug_hud")
        panel:CheckBox("Debug Reload", "trmbase_debug_reload")
    end)
    spawnmenu.AddToolMenuOption("TriggerMiku_Work", "WeaponBase", "trmbase_viewmodel", "ViewModel", "", "",
        function(panel)
        panel:ClearControls()
            panel:NumSlider(language.GetPhrase("TRMBase_OffsetX"), "trmbase_vm_offsetX", -10, 10, 1)
            panel:NumSlider(language.GetPhrase("TRMBase_OffsetY"), "trmbase_vm_offsetY", -10, 10, 1)
        panel:NumSlider(language.GetPhrase("TRMBase_OffsetZ"), "trmbase_vm_offsetZ", -10, 10, 1)
            panel:NumSlider(language.GetPhrase("TRMBase_ViewmodelFOVAim"), "trmbase_cl_viewmodelfov_aim", 0, 3, 2)
        end)
end)
